version: '3.7'

services:

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: 'clowder/clowder-fastapi:${TAG-latest}'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MINIO_SERVER_URL: minio:9000
    depends_on:
      - mongo
      - minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`clowder.docker.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=80"

  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - mongo:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  minio:
    image: quay.io/minio/minio:RELEASE.2021-11-09T03-21-45Z
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: clowder
      MINIO_ROOT_PASSWORD: clowdersecret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      # Minio Console
#      - "traefik.http.routers.minioconsole.rule=Host(`minioconsole.docker.localhost`)"
#      - "traefik.http.routers.minioconsole.service=minioConsoleService"
#      - "traefik.http.services.minioConsoleService.loadbalancer.server.port=9001"
#      - "traefik.http.services.minioConsoleService.loadbalancer.passhostheader=true"
      # Minio itself
      - "traefik.http.routers.minio.rule=Host(`minio.docker.localhost`)"
      - "traefik.http.routers.minio.service=minioService"
      - "traefik.http.services.minioService.loadbalancer.server.port=9000"
      - "traefik.http.services.minioService.loadbalancer.passhostheader=true"

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio:
  mongo:

