version: '3.3'

services:

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: 'clowder/clowder-fastapi:${TAG-latest}'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_URL: mongodb://mongo:27017
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`clowder.docker.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=80"

  mongo:
    image: mongo
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
